### ISSUE TITLE
npm package issues; PATH issues

### ISSUE THREAD

**Issue by nylen** [brianloveswords/nvm#1]
Hi @brianloveswords - the npm package `nvm` points here:

https://www.npmjs.com/package/nvm

What actually is this package?  Is it a wrapper for `nvm`, or something else?  Can you point the package at the actual source code behind it?

The reason I originally came here was to report an issue.  These instructions in the npm package readme are misleading, and I'd argue, not a good idea:

> **Setup**
> 
> You must update your path to include ./node_modules/.bin
> 
> `export PATH=./node_modules/.bin:$PATH`
> 
> Note, this is a good thing to do anyway – it will allow you to run things like jshint on a per-repo basis without having to install it globally and without having to prefix the path.

It's possible for a broken (or malicious) command to be installed via npm, overwriting your system's version and breaking things.  See https://github.com/isaacs/node-touch/issues/8 for the specific case, our developers keep running into this issue.

If users need to modify their `$PATH`, this should be done by appending `./node_modules/.bin` instead of prepending it.

Where are these instructions coming from?  I note that they're no longer present in the [current nvm readme](https://github.com/creationix/nvm).

Can you help?

**Comment by brianloveswords** [comment]
There is a storied history about why I have that package – I made a _different_ version manager and called nvm because I didn't know about the "original" one, I registered the NPM package, everyone got mad at me because of that other nvm (which I should have been more diligent about searching for a name conflict, I just noticed it was free on npm), and so I gave it over to the folks who maintain the original nvm and deleted mine so I'd stop getting issues of people mad at me for confusing them. I should probably just delete the npm package at this point because they haven't done anything with it yet and I still keep getting emails/issues about this with people being confused.

**Comment by nylen** [comment]
> I should probably just delete the npm package at this point

I suppose that would resolve the issue here...

_Edit: This was done, thanks!  https://www.npmjs.com/package/nvm now says "This is not the node version manager you are looking for"_
